In [ ]:
import pandas as pd

# Load Excel file
df = pd.read_excel("EmailSpamDataTrimmed.xls")

# print(df)

In [7]:
X = df.drop(columns=['Prediction', 'Email No.']) # all word count columns (features)
y = df['Prediction'] # the 'Prediction' column (labels: spam or legit)

# convert emails into numerical features (word frequency vectors)
x_vector = X.to_numpy()
y_vector = y.to_numpy()

print(x_vector)
print(y_vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 0 ... 1 1 0]


In [8]:
from sklearn.model_selection import train_test_split

# split dataset
x_train, x_test, y_train, y_test = train_test_split(
    x_vector,
    y_vector,
    test_size=0.2,     # 20% test size
    random_state=42,   # makes the split reproducible
    stratify=y         # keeps the same spam/legit ratio in both sets
)

print("Train set size:", x_train.shape)
print("Test set size:", x_test.shape)

Train set size: (4137, 20)
Test set size: (1035, 20)


In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

nb_model = MultinomialNB() # initialize the Naïve Bayes model

nb_model.fit(x_train, y_train) # train the model

y_pred = nb_model.predict(x_test) # make predictions on the test set

print("Naïve Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Naïve Bayes Accuracy: 0.7777777777777778
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.96      0.86       735
           1       0.77      0.34      0.47       300

    accuracy                           0.78      1035
   macro avg       0.77      0.65      0.66      1035
weighted avg       0.78      0.78      0.75      1035

